const { PrismaClient } = await import('../generated/prisma/client.ts');
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dbPath = path.join(__dirname, '..', 'dev.db');
const adapter = new PrismaBetterSqlite3({
  url: process.env.DATABASE_URL ?? `file:${dbPath}`,
});

const prisma = new PrismaClient({ adapter });

const DEFAULT_RENDER_PRESET = {
  screenNits: 700,
  bloom: 0.12,
  glassReflection: 0.08,
  grain: 0.06,
  cinematicMode: true,
};

const DEMO_POINTS = [
  {
    id: 'elevator-lobby-01',
    name: 'Elevador — Lobby Shopping Catuaí',
    slug: 'elevator-lobby-01',
    type: 'Elevadores',
    city: 'Londrina',
    description: 'Tela vertical no lobby principal do Shopping Catuaí, alto fluxo diário.',
    insertionType: 'Tela Vertical 9:16',
    targetAudience: 'Público geral — consumidores A/B',
    audienceClassification: 'Classe A/B',
    address: 'R. Maestro Andrea Nuzzi, 580 — Londrina/PR',
    thumbnailUrl: '',
    baseMediaUrl: '/placeholders/scene-01.jpg',
    baseMediaType: 'image',
    baseWidth: 1920,
    baseHeight: 1080,
    screenWidth: 1080,
    screenHeight: 1920,
    screenAspect: '9:16',
    fitMode: 'cover',
    screenSelection: JSON.stringify({
      mode: 'quad',
      corners: [
        { x: 800, y: 200 },
        { x: 1120, y: 200 },
        { x: 1120, y: 770 },
        { x: 800, y: 770 },
      ],
    }),
    renderPreset: JSON.stringify({ ...DEFAULT_RENDER_PRESET, screenNits: 500 }),
    minimumInsertions: 120,
    published: true,
    createdAt: new Date('2026-02-01T10:00:00Z'),
    updatedAt: new Date('2026-02-15T14:30:00Z'),
  },
  {
    id: 'outdoor-billboard-01',
    name: 'Frontlight — Av. Higienópolis',
    slug: 'outdoor-billboard-01',
    type: 'FrontLights',
    city: 'Londrina',
    description: 'Painel frontlight de grande formato na principal avenida comercial.',
    insertionType: 'Painel 16:9 — 9m × 3m',
    targetAudience: 'Motoristas e pedestres — alto tráfego',
    audienceClassification: 'Classe B/C',
    address: 'Av. Higienópolis, 1200 — Londrina/PR',
    thumbnailUrl: '',
    baseMediaUrl: '/placeholders/scene-02.jpg',
    baseMediaType: 'image',
    baseWidth: 3840,
    baseHeight: 2160,
    screenWidth: 3840,
    screenHeight: 2160,
    screenAspect: '16:9',
    fitMode: 'cover',
    screenSelection: JSON.stringify({
      mode: 'quad',
      corners: [
        { x: 600, y: 300 },
        { x: 3200, y: 300 },
        { x: 3200, y: 1760 },
        { x: 600, y: 1760 },
      ],
    }),
    renderPreset: JSON.stringify({ ...DEFAULT_RENDER_PRESET, screenNits: 2000, bloom: 0.18 }),
    minimumInsertions: 60,
    published: true,
    createdAt: new Date('2026-01-20T08:00:00Z'),
    updatedAt: new Date('2026-03-01T11:00:00Z'),
  },
  {
    id: 'indoor-totem-01',
    name: 'Totem — Shopping Boulevard',
    slug: 'indoor-totem-01',
    type: 'Indoors',
    city: 'Maringá',
    description: 'Totem digital interativo no corredor principal do shopping.',
    insertionType: 'Totem Vertical 9:16',
    targetAudience: 'Famílias e jovens adultos',
    audienceClassification: 'Classe B/C',
    address: 'Av. Horácio Raccanello Filho, 5400 — Maringá/PR',
    thumbnailUrl: '',
    baseMediaUrl: '/placeholders/scene-03.jpg',
    baseMediaType: 'image',
    baseWidth: 1080,
    baseHeight: 1920,
    screenWidth: 1080,
    screenHeight: 1920,
    screenAspect: '9:16',
    fitMode: 'contain',
    screenSelection: JSON.stringify({
      mode: 'quad',
      corners: [
        { x: 200, y: 150 },
        { x: 880, y: 150 },
        { x: 880, y: 1770 },
        { x: 200, y: 1770 },
      ],
    }),
    renderPreset: JSON.stringify({ ...DEFAULT_RENDER_PRESET, screenNits: 400, cinematicMode: false }),
    minimumInsertions: 200,
    published: true,
    createdAt: new Date('2026-02-10T09:00:00Z'),
    updatedAt: new Date('2026-02-10T09:00:00Z'),
  },
  {
    id: 'subway-indoor-01',
    name: 'Painel Led — Terminal Rodoviário',
    slug: 'subway-indoor-01',
    type: 'Paineis de Led',
    city: 'Londrina',
    description: 'Painel LED de alta definição na área de embarque do terminal.',
    insertionType: 'LED Indoor 16:9',
    targetAudience: 'Passageiros e acompanhantes',
    audienceClassification: 'Misto',
    address: 'Terminal Rodoviário de Londrina, R. Sergipe, 640 — Londrina/PR',
    thumbnailUrl: '',
    baseMediaUrl: '/placeholders/scene-04.jpg',
    baseMediaType: 'image',
    baseWidth: 1920,
    baseHeight: 1080,
    screenWidth: 1920,
    screenHeight: 1080,
    screenAspect: '16:9',
    fitMode: 'cover',
    screenSelection: JSON.stringify({
      mode: 'quad',
      corners: [
        { x: 400, y: 180 },
        { x: 1520, y: 180 },
        { x: 1520, y: 810 },
        { x: 400, y: 810 },
      ],
    }),
    renderPreset: JSON.stringify({ ...DEFAULT_RENDER_PRESET, screenNits: 800 }),
    minimumInsertions: 90,
    published: true,
    createdAt: new Date('2026-03-01T12:00:00Z'),
    updatedAt: new Date('2026-03-05T16:00:00Z'),
  },
  {
    id: 'backlight-maringa-01',
    name: 'Backlight — Av. Brasil',
    slug: 'backlight-maringa-01',
    type: 'BackLights',
    city: 'Maringá',
    description: 'Painel backlight retro-iluminado em avenida de alto movimento.',
    insertionType: 'Backlight 16:9 — 6m × 3m',
    targetAudience: 'Motoristas — fluxo noturno intenso',
    audienceClassification: 'Classe B/C',
    address: 'Av. Brasil, 3500 — Maringá/PR',
    thumbnailUrl: '',
    baseMediaUrl: '__video__',
    baseMediaType: 'video',
    baseWidth: 1920,
    baseHeight: 1080,
    screenWidth: 1920,
    screenHeight: 1080,
    screenAspect: '16:9',
    fitMode: 'cover',
    screenSelection: JSON.stringify({
      mode: 'quad',
      corners: [
        { x: 250, y: 200 },
        { x: 1650, y: 200 },
        { x: 1650, y: 900 },
        { x: 250, y: 900 },
      ],
    }),
    renderPreset: JSON.stringify({ ...DEFAULT_RENDER_PRESET, screenNits: 1200, bloom: 0.12 }),
    minimumInsertions: 45,
    published: true,
    createdAt: new Date('2026-02-20T10:00:00Z'),
    updatedAt: new Date('2026-02-25T14:00:00Z'),
  },
  {
    id: 'elevator-bc-01',
    name: 'Elevador — Ed. Atlântico Sul',
    slug: 'elevator-bc-01',
    type: 'Elevadores',
    city: 'Balneário Camboriú',
    description: 'Tela no elevador social do edifício residencial de alto padrão.',
    insertionType: 'Tela Vertical 9:16',
    targetAudience: 'Moradores — classe A',
    audienceClassification: 'Classe A',
    address: 'Av. Atlântica, 2200 — Balneário Camboriú/SC',
    thumbnailUrl: '',
    baseMediaUrl: '/placeholders/scene-01.jpg',
    baseMediaType: 'image',
    baseWidth: 1080,
    baseHeight: 1920,
    screenWidth: 1080,
    screenHeight: 1920,
    screenAspect: '9:16',
    fitMode: 'cover',
    screenSelection: JSON.stringify({
      mode: 'quad',
      corners: [
        { x: 200, y: 150 },
        { x: 880, y: 150 },
        { x: 880, y: 1770 },
        { x: 200, y: 1770 },
      ],
    }),
    renderPreset: JSON.stringify({ ...DEFAULT_RENDER_PRESET, screenNits: 450 }),
    minimumInsertions: 150,
    published: true,
    createdAt: new Date('2026-03-01T08:00:00Z'),
    updatedAt: new Date('2026-03-05T10:00:00Z'),
  },
  {
    id: 'led-bc-01',
    name: 'Painel Led — Av. Atlântica',
    slug: 'led-bc-01',
    type: 'Paineis de Led',
    city: 'Balneário Camboriú',
    description: 'Painel LED externo na orla, visibilidade 24h.',
    insertionType: 'LED Outdoor 16:9',
    targetAudience: 'Turistas e moradores — altíssimo fluxo',
    audienceClassification: 'Misto',
    address: 'Av. Atlântica, 4000 — Balneário Camboriú/SC',
    thumbnailUrl: '',
    baseMediaUrl: '__video__',
    baseMediaType: 'video',
    baseWidth: 1920,
    baseHeight: 1080,
    screenWidth: 3840,
    screenHeight: 2160,
    screenAspect: '16:9',
    fitMode: 'cover',
    screenSelection: JSON.stringify({
      mode: 'quad',
      corners: [
        { x: 300, y: 200 },
        { x: 1620, y: 200 },
        { x: 1620, y: 880 },
        { x: 300, y: 880 },
      ],
    }),
    renderPreset: JSON.stringify({ ...DEFAULT_RENDER_PRESET, screenNits: 2500, bloom: 0.2 }),
    minimumInsertions: 80,
    published: true,
    createdAt: new Date('2026-03-02T09:00:00Z'),
    updatedAt: new Date('2026-03-06T11:00:00Z'),
  },
  {
    id: 'frontlight-maringa-01',
    name: 'Frontlight — Rod. BR-376',
    slug: 'frontlight-maringa-01',
    type: 'FrontLights',
    city: 'Maringá',
    description: 'Painel de grande porte na rodovia de acesso à cidade.',
    insertionType: 'Frontlight 16:9 — 12m × 4m',
    targetAudience: 'Motoristas — alto fluxo rodoviário',
    audienceClassification: 'Misto',
    address: 'Rod. BR-376, km 172 — Maringá/PR',
    thumbnailUrl: '',
    baseMediaUrl: '/placeholders/scene-02.jpg',
    baseMediaType: 'image',
    baseWidth: 3840,
    baseHeight: 2160,
    screenWidth: 3840,
    screenHeight: 2160,
    screenAspect: '16:9',
    fitMode: 'cover',
    screenSelection: JSON.stringify({
      mode: 'quad',
      corners: [
        { x: 400, y: 350 },
        { x: 3400, y: 350 },
        { x: 3400, y: 1850 },
        { x: 400, y: 1850 },
      ],
    }),
    renderPreset: JSON.stringify({ ...DEFAULT_RENDER_PRESET, screenNits: 1800, bloom: 0.15 }),
    minimumInsertions: 30,
    published: true,
    createdAt: new Date('2026-02-28T10:00:00Z'),
    updatedAt: new Date('2026-03-04T12:00:00Z'),
  },
];

async function main() {
  console.log('Seeding database...');

  for (const point of DEMO_POINTS) {
    await prisma.point.upsert({
      where: { slug: point.slug },
      update: point,
      create: point,
    });
  }

  console.log(`Seeded ${DEMO_POINTS.length} demo points.`);
}

main()
  .catch((e: unknown) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
